version: '3'

services:
  postgres:
    image: postgres:latest
    restart: always
    env_file:
      - docker-compose.env
    volumes:
      - .postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    extra_hosts:
      - "host.docker.internal:172.17.0.1"

  clickhouse_server:
    image: yandex/clickhouse-server
    restart: always
    ports:
      - "8123:8123"
    env_file:
      - docker-compose.env
    volumes:
      - .clickhouse_data:/var/lib/clickhouse
    extra_hosts:
      - "host.docker.internal:10.0.10.120"

  clickhouse_client:
      image: yandex/clickhouse-client
      entrypoint:
        - /bin/sleep
      command:
        - infinity

